### ISSUE TITLE
Note icon is placed differently than that in mockup.

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/Universell#2]
On Mockup:

![image](https://user-images.githubusercontent.com/11936336/195040388-2855e2a9-62d1-4993-8fd7-2d0858992079.png)

On Staging:

![image](https://user-images.githubusercontent.com/11936336/195040536-2a4d2571-f656-410e-8089-73df71988fb9.png)

**Comment by Avijit2rath** [comment]
There are no Options in Font Awsome I will try to manage through Css.

**Comment by talhakpg** [comment]
@MayankTalwar0 Can we have some inputs here? Are we okay with such deviations or do we have a solution to this?

**Comment by MayankTalwar0** [comment]
Thanks @talhakpg If the new icon makes sense, then this could work. 

@Avijit2rath Could you send some suggestions for replacement?

**Comment by Avijit2rath** [comment]
@talhakpg No i think the icon suits fine.
