### ISSUE TITLE
Subitems should collaps when the navigation bar is collapsed

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/Universell#4]
Steps to replicate:
1. Navigate to https://testcloudhosting.com/universell-dashboard/index.html
2. Expand the navigation bar(clicking on the burger menu).
3. Expand one of the Subitems. [Test data: Dashboard]
4. Click on the burger menu to collapse the navigation bar.

Expected result:
The navigation bar should be collapsed and the subitems icon should only be seen. The subitems should also be collapsed.

Actual result:
The navigation bar is collapsed but the subitems remains expanded and parts of it can be seen along with subitems icons.

![image](https://user-images.githubusercontent.com/11936336/195078476-8ce4b1d2-0229-46d4-a94a-2a9aed88d838.png)

**Comment by Avijit2rath** [comment]
Done

**Comment by talhakpg** [comment]
@Avijit2rath I see this and many other tickets to be marked as done by you but it does not reflect on the site. Please make sure you put up a comment here when the changes are pushed to the site.
For now I have pushed all these tickets to the next sprint.

**Comment by Avijit2rath** [comment]
I have published the changes and you can see them on https://testcloudhosting.com/universell-dashboard/sitemap.html
