### ISSUE TITLE
Default view on navigating to the site should have menu collapsed

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/Universell#7]
At present when a user navigates to the site navigation bar is expanded by default. It should be collapsed.

https://www.screencast.com/t/LVYlf0XyW

**Comment by Avijit2rath** [comment]
Done !!

**Comment by Avijit2rath** [comment]
Made default the side menu closed. 
https://testcloudhosting.com/universell-dashboard/sitemap.html
